{% extends "djangooidc/base.html" %}

{% block title %}Error{% endblock %}

{% block  content %}
    <div>
        <div>OpenID Connect authentication has failed</div>
        <div>
            {% if debug %}
            <div><span>Error message is: </span>{{ error }}</div>
                {% if callback %}
                <div>Query content was:</div>
                <div>
                    <table>
                        <thead>
                        <tr>
                            <th>Key</th>
                            <th>Value</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for key,value in callback.items %}
                            <tr>
                                <td>{{ key }}</td>
                                <td>{{ value }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            <div>You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a user-friendly page.</div>
            {% else %}
                {% if op_name %}
            <div>You may want to <a href="{% url 'openid_with_op_name' op_name=op_name %}">try again</a>, or get help from the administrator.</div>
                {% else %}
            <div>You may want to get help from the administrator.</div>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}